# -*- Makefile -*-

ROOT = ..

include $(ROOT)/makefiles/Makefile.opts.gmake
include Makefile.files

##----------------------------------------------------------------------

all: $(OBJS)

clean:
	$(RM) $(OBJS) $(TARGET)

##----------------------------------------------------------------------

.PHONY: all install cloean

##----------------------------------------------------------------------
